### ISSUE TITLE
problem encountered using license_finder with cocoapods 0.38.2

### ISSUE THREAD

**Issue by scottleedavis** [pivotal/LicenseFinder#177]
This is very similar to a prior issue:
https://github.com/pivotal/LicenseFinder/issues/151

 I am happy to provide any additional information you may require to help solve this issue.  

```
license_finder
......../Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:51:in `read_plist': undefined method `expand_path' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:34:in `license_texts'
    from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:16:in `block in current_packages'
    from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:8:in `map'
    from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:8:in `current_packages'
    from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:37:in `current_packages_with_relations'
    from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:23:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:23:in `flat_map'
    from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:23:in `current_packages'
    from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/core.rb:60:in `current_packages'
    from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/core.rb:55:in `decision_applier'
    from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/cli/main.rb:26:in `action_items'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/bin/license_finder:5:in `<top (required)>'
    from /usr/bin/license_finder:23:in `load'
    from /usr/bin/license_finder:23:in `<main>'

```

**Comment by mainej** [comment]
I'm not a CocoaPods user, so bear with me... 

CocoaPods generates a [plist of license information](https://github.com/CocoaPods/CocoaPods/wiki/Acknowledgements), which license_finder parses.  The error you're seeing would occur if the plist file didn't exist.  The file is supposed to be called `Pods/Target Support Files/Pods/Pods-Acknowledgements.plist`.  We have also seen it in `Pods/Pods-Acknowledgements.plist` in older versions of CocoaPods, so we look for it in both places.

Does that file exist in your project anywhere?  If it does, does it have the above capitalization?  We may have a problem with case-sensitive file systems.

**Comment by scottleedavis** [comment]
updated to cocoapods v0.39.0 ...  same issue.



Those files are not capitalized on my system (osx 10.10.5).  Additionally, the Podfile target names are part of the plist acknowledgements filename.

e.g. with target 'ObjCSample' , the file becomes:
```
Pods/Target Support Files/Pods-ObjCSample/Pods-ObjCSample-acknowledgements.plist
``

**Comment by flavorjones** [comment]
@scottleedavis You'll note that #151 was not resolved, it was just closed because of lack of information.

Can you help us understand what's going on? Can you try cocoapods 0.37.1, which is what our test suite is using? I want to isolate whether this is a behavioral change in cocoapods, and if so what that behavioral change is.

**Comment by scottleedavis** [comment]
rolled back to cocoapods 0.37.1 and reran.  Same error message and resultant folder setup.

```
pdxdaviss03:ObjC daviss$ pod --version
0.37.1
pdxdaviss03:ObjC daviss$ license_finder
......../Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:51:in `read_plist': undefined method `expand_path' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:34:in `license_texts'
	from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:16:in `block in current_packages'
	from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:8:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_managers/cocoa_pods.rb:8:in `current_packages'
	from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:37:in `current_packages_with_relations'
	from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:23:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:23:in `flat_map'
	from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/package_manager.rb:23:in `current_packages'
	from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/core.rb:60:in `current_packages'
	from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/core.rb:55:in `decision_applier'
	from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/lib/license_finder/cli/main.rb:26:in `action_items'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/license_finder-2.0.4/bin/license_finder:5:in `<top (required)>'
	from /usr/bin/license_finder:23:in `load'
	from /usr/bin/license_finder:23:in `<main>'
```

**Comment by flavorjones** [comment]
@scottleedavis Thanks for letting us know it's not related to the version of Cocoapods. Can you help us reproduce this? I've tried, and can't get this error to be emitted, so I'm doing something different than you are.

**Comment by scottleedavis** [comment]
Apologies however I have since moved off the project.... Perhaps I was
doing something incorrectly?

**Comment by dustyburwell** [comment]
I'm seeing a similar issue. It appears that cocoapods generates `Pods/Target\ Support\ Files/Pods-<target>/Pods-<target>-acknowledgements.plist` files for each target directive listed in the Podfile. E.g. 

```
platform :ios,  '7.0'

inhibit_all_warnings!

xcodeproj 'App/App.xcodeproj'

target :TheApp, :exclusive => true do
    pod 'AFNetworking', '~> 2.5'
    pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
    pod 'iPhoneMK/MKNumberBadgeView', '~> 1.2.3'
    pod 'CardIO', '~> 3.10.1'
    pod 'AFNetworkActivityLogger', '~> 2.0'
    #pod 'HockeySDK',		'~> 3.5.0'
    pod 'CocoaLumberjack', '~> 1.8'
    pod 'JRSwizzle'
    pod 'ZXingObjC', '~> 3.0'
    pod 'ECPhoneNumberFormatter'
    pod 'RMDateSelectionViewController'
    pod 'ActionSheetPicker-3.0', '~> 1.0.9'
    pod 'MobileAppTracker', '~> 3.6'
    pod 'Facebook-iOS-SDK', '~> 3.21'
end

target :TheTests, :exclusive => true do
    pod 'AFNetworking', '~> 2.5'
    pod 'Kiwi', '~> 2.3.0'
    pod 'CocoaLumberjack', '~> 1.8'
    pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
end
```

This would result in two acknowledgement files at `Pods/Target\ Support\ Files/Pods-TheApp/Pods-TheApp-acknowledgements.plist` and `Pods/Target\ Support\ Files/Pods-TheTests/Pods-TheTests-acknowledgements.plist`. Simpler Podfiles without target directives do not result in this this, only generating acknowledgement files that are correctly detected with the current implementation.

Instead of parsing the Podfile to determine which targets to look for (a daunting task given it's Ruby), it may be simpler to use some kind of file globbing to find all acknowledgements files and assume there can be more than one.
