### ISSUE TITLE
AttributeError with pip 8.1.2 and license_finder 2.1.0

### ISSUE THREAD

**Issue by wayne-luminal** [pivotal/LicenseFinder#224]
Using pip 8.1.2, `license_finder` throws a stack trace for Python projects:

```
± license_finder
..................Traceback (most recent call last):
  File "/usr/local/lib/ruby/gems/2.3.0/gems/license_finder-2.1.0/bin/license_finder_pip.py", line 20, in <module>
    in pkg_resources.working_set.resolve(requirements)]
  File ".../lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 811, in resolve
    dist = best.get(req.key)
AttributeError: 'Requirement' object has no attribute 'key'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/json/common.rb:156:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
    from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/json/common.rb:156:in `new'
    from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/json/common.rb:156:in `parse'
    from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/json/common.rb:469:in `JSON'
    from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-2.1.0/lib/license_finder/package_managers/pip.rb:31:in `pip_output'
    from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-2.1.0/lib/license_finder/package_managers/pip.rb:7:in `current_packages'
    from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-2.1.0/lib/license_finder/package_manager.rb:60:in `current_packages_with_relations'
    from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-2.1.0/lib/license_finder/package_manager.rb:23:in `each'
    from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-2.1.0/lib/license_finder/package_manager.rb:23:in `flat_map'
    from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-2.1.0/lib/license_finder/package_manager.rb:23:in `current_packages'
    from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-2.1.0/lib/license_finder/core.rb:63:in `current_packages'
    from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-2.1.0/lib/license_finder/core.rb:58:in `decision_applier'
    from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-2.1.0/lib/license_finder/cli/main.rb:36:in `action_items'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-2.1.0/bin/license_finder:5:in `<top (required)>'
    from /usr/local/bin/license_finder:23:in `load'
    from /usr/local/bin/license_finder:23:in `<main>'
```

An example requirements file:

```
typing==3.5.1.0
```

**Comment by wayne-luminal** [comment]
Confirmed that `license_finder` works with pip 6.0 (as per the minimum requirement in the README)

```
± pip install pip==6.0
...
± license_finder
...................
Dependencies that need approval:
typing, 3.5.1.0, "Python Software Foundation License"
```

It ALSO works with 8.1 and 8.1.1. Looks like the `Requirement` class changed between 8.1.1 and 8.1.2.

**Comment by jseabold** [comment]
Semi-related discussion: https://github.com/nvie/pip-tools/issues/358

**Comment by flavorjones** [comment]
Hi,

Thanks for reporting this.

I've reproduced this issue using pip 8.1.2 in our test suite:

```
rspec features/features/package_managers/pip_spec.rb
```

This test passes using pip 8.0.2, so this is likely something that's changed between pip 8.0.x and 8.1.x.

I'll have to find some time to dig into this further; I'd welcome any suggestions you might have, as I'm only slightly familiar with the python toolchain.

**Comment by xtreme-jesse-malone** [comment]
It seems like in bin/license_finder_pip.py we get Requirement objects back which are those defined in [pip.req](https://github.com/pypa/packaging/blob/master/packaging/requirements.py#L75) but later on we call pkg_resources_.working_set.resolve which expects a [pkg_resources.Requirement](https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L2880). I'm working on a fix, making sure we use pkg_resourc.Requirement.

**Comment by josegonzalez** [comment]
@xtreme-jesse-malone Any chance of that fix making it to a release? Hasn't been one in a few months, would love to not run master :)

Also, thanks for your work on this project!
