### ISSUE TITLE
Report does not list all the installed gems

### ISSUE THREAD

**Issue by vivekkodira1** [pivotal/LicenseFinder#297]
I'm not very familiar with Ruby so my apologies if this is a noob question. 

I am trying to find licenses of all the gems installed on an instance. Regardless of which path I'm on, when I run 'gem list' I get a long list of all the installed gems. However, when I run `license_finder report`, it does not list anything. 

I tried running `license_finder report` while on root with the flag `--recursive` and see the following error:

```
[root@8484963fa169 /]# license_finder report --recursive
/usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler.rb:211:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler.rb:207:in `root'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler.rb:225:in `app_cache'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:455:in `cache_path'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/source/rubygems.rb:23:in `initialize'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/source_list.rb:12:in `new'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/source_list.rb:12:in `initialize'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/dsl.rb:22:in `new'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/dsl.rb:22:in `initialize'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/dsl.rb:10:in `new'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/dsl.rb:10:in `evaluate'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:33:in `build'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/package_managers/bundler.rb:30:in `definition'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/package_managers/bundler.rb:49:in `included_groups'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/package_managers/bundler.rb:12:in `current_packages'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/package_manager.rb:60:in `current_packages_with_relations'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/package_manager.rb:23:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/package_manager.rb:23:in `flat_map'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/package_manager.rb:23:in `current_packages'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/core.rb:63:in `current_packages'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/core.rb:58:in `decision_applier'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/license_aggregator.rb:21:in `block in aggregate_packages'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/license_aggregator.rb:19:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/license_aggregator.rb:19:in `flat_map'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/license_aggregator.rb:19:in `aggregate_packages'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/license_aggregator.rb:10:in `dependencies'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/lib/license_finder/cli/main.rb:73:in `report'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/license_finder-3.0.0/bin/license_finder:5:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/license_finder:22:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/license_finder:22:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

What am I doing wrong?

**Comment by kdykeman** [comment]
Hi vivekkodira1,

LicenseFinder is really meant to find the dependencies of Ruby based applications based on a Gemfile. So a typical usage would be to have checked out source code (such as [license finder's own repo](https://github.com/pivotal/LicenseFinder)) and to run `license_finder report` in the directory you cloned the repo into.

LicenseFinder doesn't enumerate the licenses for all gems installed on an instance.

**Comment by vivekkodira1** [comment]
Hi @kdykeman,

Thank you for taking the time to respond in detail. I will update the SO answer which brought me here accordingly.

Regards,
Vivek.

**Comment by kdykeman** [comment]
@vivekkodira1 

Thanks, it looks like you found a good path for what you needed outside of LicenseFinder.
Closing this issue.
