### ISSUE TITLE
LicenseFinder unable to parse some JSON output from NPM v5

### ISSUE THREAD

**Issue by richardowen** [pivotal/LicenseFinder#301]
To reproduce, update to the latest version of NPM (5.0.3 at the time of writing) and create a package.json with this in it:

```
{
  "dependencies": {
    "babel-core": "6.25.0"
  }
}
```

Then run `npm install` and `license_finder`

You get the following output:

```
$ license_finder
................../usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/json/common.rb:156:in `parse': 743: unexpected token at '{ (JSON::ParserError)
< truncated JSON output >
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/json/common.rb:156:in `parse'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/json/common.rb:440:in `JSON'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/lib/license_finder/package_managers/npm.rb:58:in `npm_json'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/lib/license_finder/package_managers/npm.rb:44:in `walk_dependency_tree'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/lib/license_finder/package_managers/npm.rb:11:in `block in current_packages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/lib/license_finder/package_managers/npm.rb:9:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/lib/license_finder/package_managers/npm.rb:9:in `current_packages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/lib/license_finder/package_manager.rb:60:in `current_packages_with_relations'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/lib/license_finder/package_manager.rb:23:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/lib/license_finder/package_manager.rb:23:in `flat_map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/lib/license_finder/package_manager.rb:23:in `current_packages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/lib/license_finder/core.rb:63:in `current_packages'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/lib/license_finder/core.rb:58:in `decision_applier'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/forwardable.rb:223:in `unapproved'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/lib/license_finder/cli/main.rb:37:in `action_items'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.0/bin/license_finder:5:in `<top (required)>'
	from /usr/local/bin/license_finder:22:in `load'
	from /usr/local/bin/license_finder:22:in `<main>'
```

I can see from the code that it is trying to parse the output from `npm list --json --long`. When I run that command it appears to output valid JSON (having checked the output with a tool online) so not sure why ruby is failing to parse it.

It does look like NPM made some changes to the JSON output in v5 as this is in the v5 release notes:

> --parseable and --json now work more consistently across various commands, particularly install and ls.

This works fine with NPM 4.6.1 (the latest v4 at the time of writing). It also doesn't fail with just any NPM package, so there must be something specific to babel-core or one of its dependencies.

**Comment by rwfeather** [comment]
I can confirm as well that this is happening on NPM 5.0.3, and that the output from my `npm list --json --long` is valid JSON according to jsonlint.

Is this an issue with Ruby's default parser?

**Comment by rvirani1** [comment]
Also having this issue when adding the `eslint` package
