### ISSUE TITLE
Unable to follow symbolic link for README to README.md

### ISSUE THREAD

**Issue by pts-owentran** [pivotal/LicenseFinder#318]
See https://github.com/dryruby/rack-throttle/blob/master/README

```
/usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/packages/possible_license_file.rb:16:in `binread': No such file or directory @ rb_sysopen - /usr/local/lib/ruby/gems/2.3.0/gems/rack-throttle-0.5.0/README (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/packages/possible_license_file.rb:16:in `binread'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/packages/possible_license_file.rb:16:in `text'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/packages/possible_license_file.rb:12:in `license'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/packages/license_files.rb:19:in `block in find'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/packages/license_files.rb:19:in `reject'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/packages/license_files.rb:19:in `find'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/packages/license_files.rb:9:in `find'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/package.rb:145:in `license_files'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/package.rb:131:in `licensing'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/package.rb:125:in `activations'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/package.rb:121:in `licenses'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/decision_applier.rb:47:in `with_approval'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/decision_applier.rb:30:in `block in apply_decisions'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/decision_applier.rb:30:in `map'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/decision_applier.rb:30:in `apply_decisions'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/decision_applier.rb:6:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/core.rb:58:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/core.rb:58:in `decision_applier'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/lib/license_finder/cli/main.rb:38:in `action_items'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/license_finder-3.0.1/bin/license_finder:5:in `<top (required)>'
	from /usr/local/bin/license_finder:23:in `load'
	from /usr/local/bin/license_finder:23:in `<main>'
```

**Comment by vizcay** [comment]
I was going to report exactly the same, this happens when the destination of the symbolink link (for one reason or another) doesn't exists.

**Comment by pts-owentran** [comment]
Funny. The symlink does point to a file that exists:
https://github.com/dryruby/rack-throttle/blob/master/README.md

**Comment by kdykeman** [comment]
I am able to reliably reproduce this by removing the target of a symlink. It looks like License Finder is currently assuming candidate files are readable.

**Comment by kdykeman** [comment]
PR #404 includes a fix that warns about dangling symlinks, but does not error out.
