### ISSUE TITLE
NPM stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by richardowen** [pivotal/LicenseFinder#327]
To reproduce, create a package.json with this in it:

```
{
  "dependencies": {
    "eslint": "2.13.1"
  }
}
```

Then run `npm install` and `license_finder`

You get the following output:

```
$ license_finder
................./usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.2/lib/license_finder/package_managers/npm_package.rb:41:in `flattened_dependencies': stack level too deep (SystemStackError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.2/lib/license_finder/package_managers/npm_package.rb:41:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.2/lib/license_finder/package_managers/npm_package.rb:41:in `flattened_dependencies'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.2/lib/license_finder/package_managers/npm_package.rb:41:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.2/lib/license_finder/package_managers/npm_package.rb:41:in `flattened_dependencies'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.2/lib/license_finder/package_managers/npm_package.rb:41:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.2/lib/license_finder/package_managers/npm_package.rb:41:in `flattened_dependencies'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.2/lib/license_finder/package_managers/npm_package.rb:41:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.2/lib/license_finder/package_managers/npm_package.rb:41:in `flattened_dependencies'
	 ... 8961 levels...
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/license_finder-3.0.2/bin/license_finder:5:in `<top (required)>'
	from /usr/local/bin/license_finder:22:in `load'
	from /usr/local/bin/license_finder:22:in `<main>'
```

This is using the latest version of LicenseFinder (3.0.2). It looks like this issue could have been introduced with 3214741.

**Comment by kdykeman** [comment]
Verified this is working for me as of commit '2565e6a'
