### ISSUE TITLE
missing dependencies for running standalone 

### ISSUE THREAD

**Issue by jovanmaric** [pivotal/LicenseFinder#524]
I'm having the following error on my CI:

```
$ gem install license_finder
Successfully installed rubyzip-1.2.2
Successfully installed thor-0.20.3
Successfully installed parslet-1.8.2
Successfully installed toml-0.2.0
Successfully installed with_env-1.1.0
Successfully installed xml-simple-1.1.5
Successfully installed license_finder-5.5.2
7 gems installed
$ license_finder version
5.5.2
$ license_finder
LicenseFinder::Bundler: is active
LicenseFinder::NPM: is active
LicenseFinder::Yarn: is active
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find rake-12.3.1 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/spec_set.rb:85:in `map!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/spec_set.rb:85:in `materialize'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/definition.rb:170:in `specs'
	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/definition.rb:237:in `specs_for'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/package_managers/bundler.rb:55:in `gem_details'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/package_managers/bundler.rb:44:in `details'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/package_managers/bundler.rb:15:in `current_packages'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/package_manager.rb:92:in `current_packages_with_relations'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/scanner.rb:17:in `each'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/scanner.rb:17:in `flat_map'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/scanner.rb:17:in `active_packages'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/core.rb:83:in `current_packages'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/core.rb:78:in `decision_applier'
	from /usr/local/lib/ruby/2.5.0/forwardable.rb:223:in `any_packages?'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/license_aggregator.rb:15:in `map'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	from /usr/local/bundle/gems/license_finder-5.5.2/lib/license_finder/cli/main.rb:97:in `action_items'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /usr/local/bundle/gems/license_finder-5.5.2/bin/license_finder:6:in `<top (required)>'
	from /usr/local/bundle/bin/license_finder:23:in `load'
	from /usr/local/bundle/bin/license_finder:23:in `<main>'
ERROR: Job failed: exit code 1
```

This can be replecated locally by doing the following:
```
gem uninstall --all
gem install license_finder
license_finder
```

It seems that license_finder is dependent on gems like "rake", which are only specified in the development section of the gemspec. Is this intentional design? Otherwise I could make a PR 
for this.

**Comment by xtreme-shane-lattanzio** [comment]
I actually think this is a much bigger issue than just rake. I tried to uninstall all gems when using ruby 2.4.1 and got the following

```
LicenseFinder::Bundler: is active
/Users/pivotal/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.2/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find concurrent-ruby-1.0.4 in any of the sources (Bundler::GemNotFound)
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.2/lib/bundler/spec_set.rb:85:in `map!'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.2/lib/bundler/spec_set.rb:85:in `materialize'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.2/lib/bundler/definition.rb:170:in `specs'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/bundler-1.17.2/lib/bundler/definition.rb:237:in `specs_for'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/package_managers/bundler.rb:55:in `gem_details'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/package_managers/bundler.rb:44:in `details'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/package_managers/bundler.rb:15:in `current_packages'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/package_manager.rb:92:in `current_packages_with_relations'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/scanner.rb:17:in `each'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/scanner.rb:17:in `flat_map'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/scanner.rb:17:in `active_packages'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/core.rb:83:in `current_packages'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/core.rb:78:in `decision_applier'
	from /Users/pivotal/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:223:in `any_packages?'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/license_aggregator.rb:15:in `map'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/lib/license_finder/cli/main.rb:97:in `action_items'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/license_finder-5.5.2/bin/license_finder:6:in `<top (required)>'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/bin/license_finder:23:in `load'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/bin/license_finder:23:in `<main>'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/pivotal/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

This shows that concurrent-ruby is a requirement. I imagine after installing that, we will need to install more. When installing 2.5.0 as you do, I get 

```
LicenseFinder::Bundler: is active
Traceback (most recent call last):
	27: from /Users/pivotal/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
	26: from /Users/pivotal/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
	25: from /Users/pivotal/.rvm/gems/ruby-2.5.0/bin/license_finder:23:in `<main>'
	24: from /Users/pivotal/.rvm/gems/ruby-2.5.0/bin/license_finder:23:in `load'
	23: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/bin/license_finder:6:in `<top (required)>'
	22: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	21: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	20: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	19: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	18: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/cli/main.rb:97:in `action_items'
	17: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	16: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/license_aggregator.rb:15:in `map'
	15: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
	14: from /Users/pivotal/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/forwardable.rb:223:in `any_packages?'
	13: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/core.rb:78:in `decision_applier'
	12: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/core.rb:83:in `current_packages'
	11: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/scanner.rb:17:in `active_packages'
	10: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/scanner.rb:17:in `flat_map'
	 9: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/scanner.rb:17:in `each'
	 8: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/package_manager.rb:92:in `current_packages_with_relations'
	 7: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/package_managers/bundler.rb:15:in `current_packages'
	 6: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/package_managers/bundler.rb:44:in `details'
	 5: from /Users/pivotal/.rvm/gems/ruby-2.5.0/gems/license_finder-5.5.2/lib/license_finder/package_managers/bundler.rb:55:in `gem_details'
	 4: from /Users/pivotal/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:238:in `specs_for'
	 3: from /Users/pivotal/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:171:in `specs'
	 2: from /Users/pivotal/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `materialize'
	 1: from /Users/pivotal/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `map!'
/Users/pivotal/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:91:in `block in materialize': Could not find rake-12.0.0 in any of the sources (Bundler::GemNotFound)
```

We will need to look into required gems as I don't think our team has really experimented with stuff like this with our recent changes.

**Comment by xtreme-shane-lattanzio** [comment]
@jovanmaric After speaking with the team, nobody has actually tried to use gem install recently. We typically use bundler to install LF and that will include all of the dependencies. We can try to add all of the dependencies to the gemspec but I am concerned about differences in requirements between ruby versions. Feel free to make a PR and we can take a look!

Note that these are the dependencies I have found:

```
 4869  gem install rake-12.0.0
 4870  gem install rake
 4871  gem install rake 12.0.0
 4872  gem install rake -v 12.0.0
 4873  gem install concurrent-ruby -v 1.0.4
 4874  gem install i18n -v 0.7.0
 4875  gem install minitest -v 5.10.1
 4876  gem install thread_safe -v 0.3.5
 4877  gem install tzinfo -v 1.2.2
 4878  gem install activesupport -v 5.0.1
 4879  gem install builder -v 3.2.2
 4880  gem install erubis -v 2.7.0
 4881  gem install mini_portile2 -v 2.1.0
 4882  gem install nokogiri -v 1.7.0.1
 4883  gem install rails-dom-testing -v 2.0.2
 4884  gem install loofah -v 2.0.3
 4885  gem install rails-html-sanitizer -v 1.0.3
 4886  gem install actionview -v 5.0.1
 4887  gem install rack -v 2.0.1
 4888  gem install rack-test -v 0.6.3
 4889  gem install actionpack -v 5.0.1
 4890  gem install nio4r -v 1.2.1
 4891  gem install websocket-extensions -v 0.1.2
 4892  gem install websocket-driver -v 0.6.4
 4893  gem install actioncable -v 5.0.1
 4894  gem install globalid -v 0.3.7
 4895  gem install activejob -v 5.0.1
 4896  gem install mime-types-data -v 3.2016.0521
 4898  gem install mime-types -v 3.1
 4899  gem install mail -v 2.6.4
 4901  gem install actionmailer -v 5.0.1
 4902  gem install activemodel -v 5.0.1
 4903  gem install arel -v 7.1.4
 4904  gem install activerecord -v 5.0.1
 4905  gem install public_suffix -v 2.0.5
 4906  gem install addressable -v 2.5.0
 4907  gem install ansi -v 1.5.0
 4908  gem install ast -v 2.3.0
 4909  gem install xpath -v 2.0.0
 4911  gem install capybara -v 2.11.0
 4912  gem install diff-lcs -v 1.2.5
 4913  gem install faker -v 1.7.2
 4914  gem install mixlib-shellout -v 2.3.2
 4915  gem install socksify -v 1.7.1
 4916  gem install unicode-display_width -v 1.3.0
 4917  gem install terminal-table -v 1.8.0
 4918  gem install thor -v 0.19.3
 4919  gem install jenkins_api_client -v 1.5.3
 4920  gem install method_source -v 0.8.2
 4921  gem install railties -v 5.0.1
 4922  gem install jquery-rails -v 4.2.2
 4923  gem install sprockets -v 3.7.1
 4924  gem install sprockets-rails -v 3.2.0
 4925  gem install rails -v 5.0.1
 4926  gem install jquery-minicolors-rails -v 2.2.3.0
 4927  gem install log4r -v 1.1.9
 4928  gem install mixlib-log -v 1.7.1
 4929  gem install ruby-ll -v 2.1.2
 4930  gem install oga -v 2.8
 4931  gem install rspec-support -v 3.5.0
 4932  gem install rspec-core -v 3.5.4
 4933  gem install rspec-expectations -v 3.5.0
 4934  gem install rspec-mocks -v 3.5.0
 4935  gem install rspec -v 3.5.0
 4936  gem install rspec-rails -v 3.5.2
```

**Comment by jovanmaric** [comment]
I haven't tested it, however considering that `bundle install` installs the gems either in the project dir, or in the default `gem install` directory [SO](https://stackoverflow.com/questions/11635042/where-does-bundler-store-gems) I could assume that running LF with only gems installed in the `gem install` directory could work on some systems. I'm not sure however how Bundler makes this distinction and implementations like rbenv and rvm would probably make this too hard to maintain.   

However, the problem I perceived actually wasn't caused by LF, but by using `bundle install  --path vendor` to install all gems into the local vendor dir of the respective project (makes caching easier with gitlab CI). For some reason I assumed that Bundler would point to this changed location and that LF would get this information from Bundler, while the documentation of LF clearly states:

> Make sure your dependencies are installed (with your package manager's install command: bundle install, npm install, etc.)

This resulted in LF not being able to find the installed dependencies and throwing an error on the first unfindable package (which seems to be rake locally and in the above linked dependencies as well). For some reason I linked this behaviour to LF and the rake development dependency in LF (brain fart :sweat_smile:). Therefore, sorry for wasting your time on this matter. 

However it would maybe be a good idea to have the ability to state the dependency path when using LF, like for instance a CLI flag `--path` as I assume that not everyone has their .node_modules, bundle gems etc. in their project dir and it would allow CI installs like the one I demonstrated above. I didn't have the time to look into this further than checking where the BIN_PATH leads to in `lib/license_finder.rb`, which only seems to be used by the pip package manager as seen below:

```
# lib/license_finder/package_managers/pip.rb

def pip_output
  output = `#{LicenseFinder::BIN_PATH.join('license_finder_pip.py')} #{detected_package_path}`
  JSON(output).map do |package|
    package.values_at('name', 'version', 'dependencies', 'location')
  end
end
```

What do you think of this feature?

On a side note:
The above list of dependencies were probably from the project LF was ran on, as I couldn't find LF using any of the listed rails dependencies and it shouldn't be using them.
