### ISSUE TITLE
Pull request 572 caused regression on non ruby projects

### ISSUE THREAD

**Issue by knightzac19** [pivotal/LicenseFinder#600]
With the release of 5.9.0 #572 now causes a error when run on non-ruby projects that don't have the BUNDLE_GEMFILE env var set because File.basename receives nil when the scanner initializes.

A workaround is setting BUNDLE_GEMFILE=Gemfile at the moment, but the real fix is to set it by default in the `bundler.rb` file like it had originally. The reason tests passed is because bundler was used to run the tests thus BUNDLE_GEMFILE was always set and the code saw the variable all the time. If you set BUNDLE_GEMFILE to nil before running the tests you'll more then likely see the failure.

```
Traceback (most recent call last):
	24: from /usr/share/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
	23: from /usr/share/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
	22: from /usr/share/rvm/gems/ruby-2.6.1/bin/license_finder:23:in `<main>'
	21: from /usr/share/rvm/gems/ruby-2.6.1/bin/license_finder:23:in `load'
	20: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/bin/license_finder:6:in `<top (required)>'
	19: from /usr/share/rvm/gems/ruby-2.6.1/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	18: from /usr/share/rvm/gems/ruby-2.6.1/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	17: from /usr/share/rvm/gems/ruby-2.6.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	16: from /usr/share/rvm/gems/ruby-2.6.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	15: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/cli/main.rb:100:in `action_items'
	14: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	13: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/license_aggregator.rb:15:in `map'
	12: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
	11: from /usr/share/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/forwardable.rb:224:in `any_packages?'
	10: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/core.rb:78:in `decision_applier'
	 9: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/core.rb:83:in `current_packages'
	 8: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/scanner.rb:15:in `active_packages'
	 7: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/scanner.rb:24:in `active_package_managers'
	 6: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/scanner.rb:24:in `each'
	 5: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/scanner.rb:25:in `block in active_package_managers'
	 4: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/package_manager.rb:70:in `active?'
	 3: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/package_manager.rb:75:in `detected_package_path'
	 2: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/package_managers/bundler.rb:31:in `possible_package_paths'
	 1: from /usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/package_managers/bundler.rb:94:in `gemfile'
/usr/share/rvm/gems/ruby-2.6.1/gems/license_finder-5.9.0/lib/license_finder/package_managers/bundler.rb:94:in `basename': no implicit conversion of nil into String (TypeError)
```

@xtreme-shane-lattanzio

**Comment by xtreme-shane-lattanzio** [comment]
@knightzac19 @richardowen On it! Thanks for bringing this up. We are testing the fix now and then will rerelease. Sorry for the inconvenience!

**Comment by knightzac19** [comment]
@xtreme-shane-lattanzio Looks like that's fixed now, thanks.
