### ISSUE TITLE
Unable to find a spec satisfying when using gemspec and bundler

### ISSUE THREAD

**Issue by micheelengronne** [pivotal/LicenseFinder#603]
When using bundler with gemspec to develop a gem, licensefinder does not detect the gem.

I first run `bundle install --path=.` to create the lockfile with a Gemfile:

```
source 'https://rubygems.org'

gemspec
```

It creates the following spec for the developed gem:

```
PATH
  remote: .
  specs:
    GEMTOTEST (1.7.1)
      GEMTOTESTDEPENDENCY (~> 4)
```

Then I run license_finder and it reports an error:

```
LicenseFinder::Bundler: is active
/var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:39:in `block in for': Unable to find a spec satisfying GEMTOTEST (>= 0) in the set. Perhaps the lockfile is corrupted? (Bundler::GemNotFound)
	from /var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:21:in `loop'
	from /var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:21:in `for'
	from /var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:79:in `materialize'
	from /var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/definition.rb:170:in `specs'
	from /var/lib/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/definition.rb:237:in `specs_for'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/package_managers/bundler.rb:62:in `gem_details'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/package_managers/bundler.rb:47:in `details'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/package_managers/bundler.rb:15:in `current_packages'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/package_manager.rb:97:in `current_packages_with_relations'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/scanner.rb:17:in `each'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/scanner.rb:17:in `flat_map'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/scanner.rb:17:in `active_packages'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/core.rb:83:in `current_packages'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/core.rb:78:in `decision_applier'
	from /usr/lib/ruby/2.5.0/forwardable.rb:223:in `acknowledged'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/license_aggregator.rb:51:in `block in aggregate_packages'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/license_aggregator.rb:49:in `each'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/license_aggregator.rb:49:in `flat_map'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/license_aggregator.rb:49:in `aggregate_packages'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/license_aggregator.rb:11:in `dependencies'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/lib/license_finder/cli/main.rb:139:in `report'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /home/licenses/.bundle/lib/ruby/2.5.0/gems/license_finder-5.9.1/bin/license_finder:6:in `<top (required)>'
	from /home/licenses/.bundle/bin/license_finder:29:in `load'
	from /home/licenses/.bundle/bin/license_finder:29:in `<main>'
```
license_finder seems to not understand the spec remote:.

**Comment by micheelengronne** [comment]
Nevermind. My custom Docker image messed up between the Gemfile to install license_finder and the Gemfile to test.
