### ISSUE TITLE
error when gem points to a git repo

### ISSUE THREAD

**Issue by Manifaust** [pivotal/LicenseFinder#615]
Running license finder fails when the Gemfile has a gem that points to a git repo.

Example Gemfile:
```
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'loaf', git: 'https://github.com/piotrmurach/loaf.git'
```

Error log:

```
$ license_finder report --project-path=/tmp/example-project --prepare
LicenseFinder::Bundler: is active
Traceback (most recent call last):
	34: from /usr/share/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	33: from /usr/share/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	32: from /usr/share/rvm/gems/ruby-2.6.3/bin/license_finder:23:in `<main>'
	31: from /usr/share/rvm/gems/ruby-2.6.3/bin/license_finder:23:in `load'
	30: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/bin/license_finder:6:in `<top (required)>'
	29: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	28: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	27: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	26: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	25: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/cli/main.rb:139:in `report'
	24: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:11:in `dependencies'
	23: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `aggregate_packages'
	22: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `flat_map'
	21: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `each'
	20: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:51:in `block in aggregate_packages'
	19: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:224:in `acknowledged'
	18: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/core.rb:78:in `decision_applier'
	17: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/core.rb:83:in `current_packages'
	16: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `active_packages'
	15: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `flat_map'
	14: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `each'
	13: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_manager.rb:97:in `current_packages_with_relations'
	12: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:15:in `current_packages'
	11: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:47:in `details'
	10: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:62:in `gem_details'
	 9: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/definition.rb:237:in `specs_for'
	 8: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/definition.rb:170:in `specs'
	 7: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `materialize'
	 6: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `map!'
	 5: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/spec_set.rb:84:in `block in materialize'
	 4: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/lazy_specification.rb:76:in `__materialize__'
	 3: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/git.rb:167:in `specs'
	 2: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/path.rb:100:in `local_specs'
	 1: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/git.rb:200:in `load_spec_files'
/usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/path.rb:198:in `load_spec_files': The path `/tmp/example-project/bundler/gems/loaf-001dfad83616` does not exist. (Bundler::PathError)
	34: from /usr/share/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	33: from /usr/share/rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	32: from /usr/share/rvm/gems/ruby-2.6.3/bin/license_finder:23:in `<main>'
	31: from /usr/share/rvm/gems/ruby-2.6.3/bin/license_finder:23:in `load'
	30: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/bin/license_finder:6:in `<top (required)>'
	29: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	28: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	27: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	26: from /usr/share/rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	25: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/cli/main.rb:139:in `report'
	24: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:11:in `dependencies'
	23: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `aggregate_packages'
	22: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `flat_map'
	21: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:49:in `each'
	20: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/license_aggregator.rb:51:in `block in aggregate_packages'
	19: from /usr/share/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:224:in `acknowledged'
	18: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/core.rb:78:in `decision_applier'
	17: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/core.rb:83:in `current_packages'
	16: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `active_packages'
	15: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `flat_map'
	14: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/scanner.rb:17:in `each'
	13: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_manager.rb:97:in `current_packages_with_relations'
	12: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:15:in `current_packages'
	11: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:47:in `details'
	10: from /usr/share/rvm/gems/ruby-2.6.3/gems/license_finder-5.9.2/lib/license_finder/package_managers/bundler.rb:62:in `gem_details'
	 9: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/definition.rb:237:in `specs_for'
	 8: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/definition.rb:170:in `specs'
	 7: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `materialize'
	 6: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `map!'
	 5: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/spec_set.rb:84:in `block in materialize'
	 4: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/lazy_specification.rb:76:in `__materialize__'
	 3: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/git.rb:167:in `specs'
	 2: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/path.rb:100:in `local_specs'
	 1: from /usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/git.rb:199:in `load_spec_files'
/usr/share/rvm/gems/ruby-2.6.3/gems/bundler-2.0.2/lib/bundler/source/git.rb:203:in `rescue in load_spec_files': https://github.com/piotrmurach/loaf.git (at master@001dfad) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
```

**Comment by xtreme-vikram-yadav** [comment]
This issue only exists when license_finder is run with --project-path=`project_path` option outside the `project_path`.

**Comment by Haegin** [comment]
@xtreme-vikram-yadav I'm running into this error just running `license_finder` from the root directory of my project with no arguments.

**Comment by mvz** [comment]
I've just started seeing this issue with version 6. version 5.11.1 is fine.

**Comment by xtreme-shane-lattanzio** [comment]
https://github.com/pivotal/LicenseFinder/pull/701 fixes this.

**Comment by mvz** [comment]
@xtreme-shane-lattanzio I just tried with license_finder 6.2.0, which should include #701, and this bug still occurs. When I run with `--debug` I also don't see any messages indicating `bundle install` is run.
