### ISSUE TITLE
Crash when Python 2 is installed as python rather than python2

### ISSUE THREAD

**Issue by sgravrock** [pivotal/LicenseFinder#662]
I have a Mac OS 10.14.6 system which has `python` and `python2.7` commands, both of which are Python 2.7, but no `python2` command. When I try to run License Finder, it tries to run the nonexistent `python2` and crashes:

```
$ bundle exec license_finder
LicenseFinder::Bundler: is active
LicenseFinder::NPM: is active
LicenseFinder::Pip: is active
LicenseFinder::Bower: is active
LicenseFinder::Bower: is not installed
bundler: failed to load command: license_finder (/Users/steve/.rbenv/versions/2.4.1/bin/license_finder)
Errno::ENOENT: No such file or directory - python2
  /Users/steve/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-5.11.1/lib/license_finder/package_managers/pip.rb:60:in ``'
  /Users/steve/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-5.11.1/lib/license_finder/package_managers/pip.rb:60:in `pip_output'
  /Users/steve/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-5.11.1/lib/license_finder/package_managers/pip.rb:16:in `current_packages'
  /Users/steve/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-5.11.1/lib/license_finder/package_manager.rb:101:in `current_packages_with_relations'
[...]
```

I tried to work around the problem by creating a `python2` symlink, but it turns out that Python crashes on startup if you do that. License Finder doesn't detect that, tries to parse the output of `license_finder_pip.py` as JSON, and crashes:

```
$ bundle exec license_finder
LicenseFinder::Bundler: is active
LicenseFinder::NPM: is active
LicenseFinder::Pip: is active
LicenseFinder::Bower: is active
LicenseFinder::Bower: is not installed
python2: realpath couldn't resolve "/usr/bin/python2"
bundler: failed to load command: license_finder (/Users/steve/.rbenv/versions/2.4.1/bin/license_finder)
JSON::ParserError: 743: unexpected token at ''
  /Users/steve/.rbenv/versions/2.4.1/lib/ruby/2.4.0/json/common.rb:156:in `parse'
  /Users/steve/.rbenv/versions/2.4.1/lib/ruby/2.4.0/json/common.rb:156:in `parse'
  /Users/steve/.rbenv/versions/2.4.1/lib/ruby/2.4.0/json/common.rb:440:in `JSON'
  /Users/steve/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-5.11.1/lib/license_finder/package_managers/pip.rb:61:in `pip_output'
  /Users/steve/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-5.11.1/lib/license_finder/package_managers/pip.rb:16:in `current_packages'
  /Users/steve/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-5.11.1/lib/license_finder/package_manager.rb:101:in `current_packages_with_relations'
[...]
```

**Comment by xtreme-shane-lattanzio** [comment]
@sgravrock Pushed a quick fix for this here: 5655f60e671dc4c247bb05138ed35b05cda9cdc7 . We do need to have a better way of supporting both python versions for sure. Related issue: https://github.com/pivotal/LicenseFinder/issues/646

**Comment by ericwb** [comment]
FYI, Python2 is end-of-life as of Jan 1, 2020.  https://www.python.org/doc/sunset-python-2/

**Comment by sgravrock** [comment]
Thanks for the quick fix.

I don't have an opinion about whether License Finder should continue to support Python 2 projects now that we're past EOL, but it would be good to see it continue to work for Python 3 projects on machines that have Python 2 installed. I suspect that'll be a common scenario for some time to come.
