### ISSUE TITLE
Default install errors out

### ISSUE THREAD

**Issue by jayzalowitz** [pivotal/LicenseFinder#706]
```
Jays-MBP:fxxxxxx jayzalowitz$ license_finder 
/Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/decisions.rb:201:in `block in restore': undefined method `whitelist' for #<LicenseFinder::Decisions:0x007f84de9a98f8> (NoMethodError)
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/decisions.rb:200:in `each'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/decisions.rb:200:in `restore'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/decisions.rb:188:in `fetch_saved'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/decisions_factory.rb:8:in `decisions'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/core.rb:56:in `decisions'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/core.rb:48:in `project_name'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/core.rb:94:in `options'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/core.rb:36:in `initialize'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/license_aggregator.rb:39:in `new'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/license_aggregator.rb:39:in `block in finders'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/license_aggregator.rb:37:in `map'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/license_aggregator.rb:37:in `finders'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/lib/license_finder/cli/main.rb:108:in `action_items'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/license_finder-6.0.0/bin/license_finder:6:in `<top (required)>'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/bin/license_finder:22:in `load'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/bin/license_finder:22:in `<main>'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/bin/ruby_executable_hooks:24:in `eval'
	from /Users/jayzalowitz/.rbenv/versions/2.4.1/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by jayzalowitz** [comment]
turns out someone had put an old version in there.
