### ISSUE TITLE
license_finder crashes with "rebar list-deps"

### ISSUE THREAD

**Issue by dumbbell** [pivotal/LicenseFinder#759]
In the Norsk pipeline for RabbitMQ, we get the following crash from `license_finder`:

```
Running GOPATH=/tmp/d20200630-1298-toywh  license_finder report --save='lf-results.json' --prepare --project-path='/tmp/d20200630-1298-toywh/src/20200630-1298-oon9m' --format=json --columns=name version install_path licenses package_manager homepage --gradle_include_groups --maven_include_groups --sbt_include_groups --go_full_version --python-version=3 --log_directory ~/lf_logs/20200630-1298-oon9m with {}
LicenseFinder::Rebar: is active
LicenseFinder scanning has failed. More information:

LicenseFinder command:
GOPATH=/tmp/d20200630-1298-toywh  license_finder report --save='lf-results.json' --prepare --project-path='/tmp/d20200630-1298-toywh/src/20200630-1298-oon9m' --format=json --columns=name version install_path licenses package_manager homepage --gradle_include_groups --maven_include_groups --sbt_include_groups --go_full_version --python-version=3 --log_directory ~/lf_logs/20200630-1298-oon9m

LicenseFinder stdout:
LicenseFinder::Rebar: is active

LicenseFinder stderr:
/usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/package_managers/rebar.rb:36:in `rebar_ouput': Command 'rebar list-deps' failed to execute:  (RuntimeError)
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/package_managers/rebar.rb:12:in `current_packages'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/package_manager.rb:101:in `current_packages_with_relations'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/scanner.rb:36:in `each'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/scanner.rb:36:in `flat_map'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/scanner.rb:36:in `active_packages'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/core.rb:83:in `current_packages'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/core.rb:78:in `decision_applier'
	from /usr/share/rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/forwardable.rb:229:in `acknowledged'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/license_aggregator.rb:51:in `block in aggregate_packages'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/license_aggregator.rb:49:in `each'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/license_aggregator.rb:49:in `flat_map'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/license_aggregator.rb:49:in `aggregate_packages'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/license_aggregator.rb:11:in `dependencies'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/lib/license_finder/cli/main.rb:148:in `report'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /usr/share/rvm/gems/ruby-2.7.1/gems/license_finder-6.6.0/bin/license_finder:6:in `<top (required)>'
	from /usr/share/rvm/gems/ruby-2.7.1/bin/license_finder:23:in `load'
	from /usr/share/rvm/gems/ruby-2.7.1/bin/license_finder:23:in `<main>'
```

The repository in this example is:
https://github.com/zhongwencool/eetcd

**Comment by xtreme-shane-lattanzio** [comment]
Fixed in: https://github.com/pivotal/LicenseFinder/commit/93680110da059ebfbd2e33802301e3e9672e1978

https://github.com/pivotal/LicenseFinder/commit/b20e7444c147d8dbfa46eb4e8e549e03be751e02
