### ISSUE TITLE
Failing in GitHub Actions workflow

### ISSUE THREAD

**Issue by veganstraightedge** [pivotal/LicenseFinder#785]
Hi Pivots 👋🏻

I'm trying to use `license_finder` in a GitHub Actions workflow in a Rails app.

Out of the box (`rails new`) Rails app repo isolated test:
https://github.com/hoverinc/license_finder_github_actions_test

Here's the workflow YAML:
https://github.com/hoverinc/license_finder_github_actions_test/blob/main/.github/workflows/license_finder.yml

```yaml
on: [push]

name: License Finder

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@master

      - name: Install dependencies
        run: |
          gem install license_finder  --no-document
      - name: Run license finder
        run: |
          license_finder
```

I get some variation of this error:

```
LicenseFinder::Bundler: is active
/home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find activesupport-5.2.4.4 in any of the sources (Bundler::GemNotFound)
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/package_managers/bundler.rb:66:in `gem_details'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/package_managers/bundler.rb:51:in `details'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/package_managers/bundler.rb:16:in `current_packages'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/package_manager.rb:101:in `current_packages_with_relations'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/scanner.rb:36:in `each'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/scanner.rb:36:in `flat_map'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/scanner.rb:36:in `active_packages'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/core.rb:83:in `current_packages'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/core.rb:78:in `decision_applier'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/2.6.0/forwardable.rb:224:in `any_packages?
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/license_aggregator.rb:15:in `map'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/cli/main.rb:108:in `action_items'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  from /home/runner/.rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/license_finder-6.9.0/bin/license_finder:6:in `<top (required)>'
  from /home/runner/.rubies/ruby-2.6.5/bin/license_finder:23:in `load'
  from /home/runner/.rubies/ruby-2.6.5/bin/license_finder:23:in `<main>'
Error: Process completed with exit code 1.
```

I've also tried `bundle`ing which had it's own problems.
I'd prefer to only install this gem and its dependencies, for faster setup and runtime. 

***

Am I doing something wrong?
If so, how can I correct this?

**Comment by xtreme-shane-lattanzio** [comment]
Hi @veganstraightedge ! LF has many dependencies and will depend on what package manager you actually care about. I wonder if it will help you to use the license finder docker image on dockerhub for this job? That will ensure that everything that is required, will be installed. Let me know if this helps!

**Comment by veganstraightedge** [comment]
@xtreme-andy-shen What dependencies does LicenseFinder have that aren't also installed when I run `gem install license_finder`?

**Comment by xtreme-shane-lattanzio** [comment]
@veganstraightedge I think you are running into the issue here: https://github.com/pivotal/LicenseFinder/issues/524 The fix is to bundle install which will install all dependencies. There is also the issue of where the gems are actually installed which is why there is some stuff there about bundler pathing.

**Comment by veganstraightedge** [comment]
Ok. That worked. I'd prefer not to have to `bundle` the whole app to be able to run `license_finder` in a CI check. But it got the job done.

Running `bundle` from scratch takes several minutes (namely because of some C extension gems), but I was able to avoid running the whole workflow on most pushes by adding this to the top of GitHub Actions workflow:

```yaml
on:
  push:
    paths:
    - 'Gemfile*'
```
