### ISSUE TITLE
license_finder fails with NoSuchMethodError

### ISSUE THREAD

**Issue by mmacbeth-silvercloud** [pivotal/LicenseFinder#798]
I've installed the latest version of LicenseFinder as of today (21 Nov) on MacOS 10.15.7 running ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19].  LicenseFinder fails when started with the following stack trace when run as my normal user, or when running via sudo:

`
Traceback (most recent call last):
	21: from /usr/local/bin/license_finder:23:in `<main>'
	20: from /usr/local/bin/license_finder:23:in `load'
	19: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/bin/license_finder:6:in `<top (required)>'
	18: from /Library/Ruby/Gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	17: from /Library/Ruby/Gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	16: from /Library/Ruby/Gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	15: from /Library/Ruby/Gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	14: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/cli/main.rb:108:in `action_items'
	13: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	12: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/license_aggregator.rb:37:in `finders'
	11: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/license_aggregator.rb:37:in `map'
	10: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/license_aggregator.rb:39:in `block in finders'
	 9: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/license_aggregator.rb:39:in `new'
	 8: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/core.rb:36:in `initialize'
	 7: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/core.rb:94:in `options'
	 6: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/core.rb:48:in `project_name'
	 5: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/core.rb:56:in `decisions'
	 4: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/decisions_factory.rb:8:in `decisions'
	 3: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/decisions.rb:273:in `fetch_saved'
	 2: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/decisions.rb:284:in `restore'
	 1: from /Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/decisions.rb:284:in `each'
/Library/Ruby/Gems/2.6.0/gems/license_finder-6.9.0/lib/license_finder/decisions.rb:285:in `block in restore': undefined method `whitelist' for #<LicenseFinder::Decisions:0x00007f90e994de10> (NoMethodError)
`

**Comment by mmacbeth-silvercloud** [comment]
One note: license finder v5.11.1 does not fail in the same way.

**Comment by Pivotal-Jeff-Jun** [comment]
@mmacbeth-silvercloud 
Since v6.0.0, LicenseFinder has started using `permitted_license` instead of `whitelist`.
[Link to commit](https://github.com/pivotal/LicenseFinder/commit/a40b22fda11b3a0efbb3c0a021381534bc998dd9), [Link to Change log](https://github.com/pivotal/LicenseFinder/blob/master/CHANGELOG.md#changed-8)

If you are using a decisions file, you will have to edit the entries to use `permit` instead of `whitelist`

**Comment by mmacbeth-silvercloud** [comment]
The error came up the first time I ran LicenseFinder - I wasn't using a permitted license or whitelist file at the time.

**Comment by Pivotal-Jeff-Jun** [comment]
I have few questions to help you debug this issue.
- Do you use `--decisions-file` flag when calling LicenseFinder?
- Do you have `doc/dependency_decisions.yml` file in your repo?

Could you share the license finder command you were calling which gave you this error?

**Comment by mmacbeth-silvercloud** [comment]
No, I wasn’t using thre –decisions-file flag.  Hoewever, I just realized a previous employee had left a doc/dependency_decisions.yml file inside our repo.  Could that be the issue?

I’m willing to chalk this up to my own user error.  However, a friendlier error message indicating I’m being dumb would be helpful too. 😊

**Comment by Pivotal-Jeff-Jun** [comment]
Oh, yes. That could be the reason why.
I suggest looking into `doc/dependency_decisions.yml` file and replace `:whitelist` to `:permit`

Thanks for the feedback, will bring this up to the team.
