### ISSUE TITLE
bundle exec license_finder does not work, no output

### ISSUE THREAD

**Issue by hubertjakubiak** [pivotal/LicenseFinder#819]
but it started to return some output when I force below method to return false:

```
def go_files_exist?
  return false

  !Dir[project_path.join('**/*.go')].empty?
end
```
in file `/Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.0.0/lib/license_finder/package_managers/go_15vendorexperiment.rb`

I'm new to this gem. I installed it via Gemfile by adding `gem 'license_finder', :group => :development`

**Comment by hubertjakubiak** [comment]
I found option `--enabled-package-managers bundler` to narrow the check, but it gives me the error:

```
bundle exec license_finder --enabled-package-managers bundler
ERROR: "license_finder action_items" was called with arguments ["--enabled-package-managers", "bundler"]
Usage: "license_finder action_items"
Deprecation warning: Thor exit with status 0 on errors. To keep this behavior, you must define `exit_on_failure?` in `LicenseFinder::CLI::Main`
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
```

**Comment by hubertjakubiak** [comment]
I solved this error above by updating gem version:

```
Fetching license_finder 6.12.0 (was 6.0.0)
Installing license_finder 6.12.0 (was 6.0.0)
```
so maybe `gem 'license_finder', :group => :development` could be updated in docs to use some version 🤔 

I still have problem with basic command `bundle exec license_finder`. It freezes forever like:

```
bundle exec license_finder
	^CTraceback (most recent call last):
	22: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `<main>'
	21: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `eval'
	20: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/bin/license_finder:23:in `<main>'
	19: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/bin/license_finder:23:in `load'
	18: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/bin/license_finder:6:in `<top (required)>'
	17: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	16: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	15: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	14: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	13: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/cli/main.rb:112:in `action_items'
	12: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	11: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/license_aggregator.rb:15:in `map'
	10: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
	 9: from /Users/hubertjakubiak/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/forwardable.rb:229:in `any_packages?'
	 8: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/core.rb:78:in `decision_applier'
	 7: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/core.rb:83:in `current_packages'
	 6: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/scanner.rb:40:in `active_packages'
	 5: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/scanner.rb:49:in `active_package_managers'
	 4: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/scanner.rb:49:in `each'
	 3: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/scanner.rb:50:in `block in active_package_managers'
	 2: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/package_managers/go_15vendorexperiment.rb:13:in `active?'
	 1: from /Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/package_managers/go_15vendorexperiment.rb:17:in `go_files_exist?'
/Users/hubertjakubiak/.rvm/gems/ruby-2.7.2/gems/license_finder-6.12.0/lib/license_finder/package_managers/go_15vendorexperiment.rb:17:in `[]': Interrupt
```

**Comment by xtreme-shane-lattanzio** [comment]
Hey @hubertjakubiak  Im not really sure what is going on here. Is there a sample project or something to help clarify? It is true that `--enabled-package-managers` was added in 6.10.0. After that make sure you have the required dependencies to run LF. There is LF docker image you can use to ensure this. Or you could install the required stuff locally that you need specifically for you project. i.e if you are using go, you should only need go stuff.

**Comment by hubertjakubiak** [comment]
I used command `bundle exec license_finder --enabled-package-managers bundler` which works and I moved forward.
