### ISSUE TITLE
Could not find addressable-2.4.0 in any of the sources

### ISSUE THREAD

**Issue by chatziparaskewas** [pivotal/LicenseFinder#828]
While license_finder is working nicely on Maven, NPM, etc. projects. Something triggers the below problem one way or the other. This happens with LF running from the command line (gem install), via Gemfile+bundle exec or via Docker.

Unfortunately, I cannot attach the project causing the issue.

The log below is from running Gemfile+bundle exec. The file /usr/bin/license_finder is physically existing.
Trying to add addressable-2.4.0 manually (gem install) does not resolve the issue. This is only the first missing dependency of many more and finally it ends in a dead end (I tried Ruby 2.5.5 and 3.0.1).

license_finder: 6.13.0
Ruby: 2.5.5
OS: CentOS Linux release 8.3.2011

------------------------------------
LicenseFinder::GoModules: is not active
LicenseFinder::GoDep: is not active
LicenseFinder::GoWorkspace: is not active
LicenseFinder::Go15VendorExperiment: is not active
LicenseFinder::Glide: is not active
LicenseFinder::Gvt: is not active
LicenseFinder::Govendor: is not active
LicenseFinder::Trash: is not active
LicenseFinder::Dep: is not active
LicenseFinder::Bundler: is active
LicenseFinder::NPM: is not active
LicenseFinder::Pip: is not active
LicenseFinder::Yarn: is not active
LicenseFinder::Bower: is not active
LicenseFinder::Maven: is not active
LicenseFinder::Gradle: is not active
LicenseFinder::CocoaPods: is not active
LicenseFinder::Rebar: is not active
LicenseFinder::Erlangmk: is not active
LicenseFinder::Nuget: is not active
LicenseFinder::Carthage: is not active
LicenseFinder::Mix: is not active
LicenseFinder::Conan: is not active
LicenseFinder::Sbt: is not active
LicenseFinder::Cargo: is not active
LicenseFinder::Dotnet: is not active
LicenseFinder::Composer: is not active
LicenseFinder::Pipenv: is not active
LicenseFinder::Conda: is not active
LicenseFinder::Spm: is not active
LicenseFinder::Bundler: is installed
LicenseFinder::Bundler: including groups [:test]
bundler: failed to load command: license_finder (/usr/bin/license_finder)
Traceback (most recent call last):
	40: from /home/xxx/bin/bundle:23:in `<main>'
	39: from /home/xxx/bin/bundle:23:in `load'
	38: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/exe/bundle:37:in `<top (required)>'
	37: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	36: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/exe/bundle:49:in `block in <top (required)>'
	35: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/cli.rb:24:in `start'
	34: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	33: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/cli.rb:30:in `dispatch'
	32: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	31: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	30: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	29: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/cli.rb:494:in `exec'
	28: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:28:in `run'
	27: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:63:in `kernel_load'
	26: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:63:in `load'
	25: from /usr/bin/license_finder:23:in `<top (required)>'
	24: from /usr/bin/license_finder:23:in `load'
	23: from /usr/share/gems/gems/license_finder-6.13.0/bin/license_finder:6:in `<top (required)>'
	22: from /home/xxx/.gem/ruby/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	21: from /home/xxx/.gem/ruby/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	20: from /home/xxx/.gem/ruby/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	19: from /home/xxx/.gem/ruby/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	18: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/cli/main.rb:112:in `action_items'
	17: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	16: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/license_aggregator.rb:15:in `map'
	15: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
	14: from /usr/share/ruby/forwardable.rb:223:in `any_packages?'
	13: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/core.rb:78:in `decision_applier'
	12: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/core.rb:83:in `current_packages'
	11: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/scanner.rb:42:in `active_packages'
	10: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/scanner.rb:42:in `flat_map'
	 9: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/scanner.rb:42:in `each'
	 8: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/package_manager.rb:105:in `current_packages_with_relations'
	 7: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/package_managers/bundler.rb:16:in `current_packages'
	 6: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/package_managers/bundler.rb:51:in `details'
	 5: from /usr/share/gems/gems/license_finder-6.13.0/lib/license_finder/package_managers/bundler.rb:66:in `gem_details'
	 4: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/definition.rb:253:in `specs_for'
	 3: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/definition.rb:183:in `specs'
	 2: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/spec_set.rb:90:in `materialize'
	 1: from /home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/spec_set.rb:90:in `map!'
/home/xxx/.gem/ruby/gems/bundler-2.2.17/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find addressable-2.4.0 in any of the sources (Bundler::GemNotFound)

**Comment by nbibler** [comment]
@chatziparaskewas: What version of bundler are you using with this project? Do both a `bundle version` from the command line and check the Gemfile.lock at the bottom there is a `BUNDLED WITH` section with a version number.

I ask because I've noticed issues with license_finder locating Rubygems with the recent bundler releases (2.2.17 for sure, but downgrading to 2.1.4 fixes it).

**Comment by chatziparaskewas** [comment]
I will try, might take some time tough. However, as said in the original post, it does not matter where license finder is run from: command line, Gemfile + bundler or Docker. The problem exists for all three variants.

**Comment by xtreme-shane-lattanzio** [comment]
If you are running in the docker image and you are still getting Gem issues, it may be a problem with bundler itself. Everything in that image should be what you need. If you do get it working on a different version of bundler, let us know and we will look into problems with latest versions. The live image is using 2.2.13 and I am wondering if it is not compatible with your project. You may also want to make sure you do not have a bad `.bundle/config` file

**Comment by ehdieunguyen** [comment]
I had the same above issue on `6.14.1` when I run the project inside the docker container. My solution is that I change the code of this line https://github.com/pivotal/LicenseFinder/blob/master/lib/license_finder/package_managers/bundler.rb#L30 to the below:

```
 gem_path = "lf-bundler-gems"
```

I guess that the gem was installed at two places but the bundler only looking at one place, so it raises that exception. 

![2021-06-29-180721_1558x649_scrot](https://user-images.githubusercontent.com/39895269/123787352-e6c99800-d904-11eb-8682-85476b221bbd.png)

**Comment by nbibler** [comment]
I was able to incorporate @benjessop12's suggestion into [faraday-detailed_logger](https://github.com/envylabs/faraday-detailed_logger/blob/ae5bcc4e5763240e24a620fb849600c44597e8ed/.github/workflows/tests.yml#L15-L22) and it appears to correct the bundler/license_finder incompatibility:

```diff
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
index b885c6c..9a0deb4 100644
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -10,10 +10,16 @@ jobs:
           ruby-version: "2.7"
       - name: "Run Tests"
         run: "bundle exec rake spec"
-      - name: "Check Licenses"
-        run: "bundle exec license_finder --quiet"
       - name: "Check Ruby Style"
         run: "bundle exec rubocop -c ./.rubocop.yml -fq"
+      - name: "Check Licenses"
+        run: |
+          # Forcibly set Bundler platform to patch for https://github.com/pivotal/LicenseFinder/issues/828
+          bundle config --local deployment false
+          bundle lock --add-platform x86_64-linux
+          bundle config --local deployment true
+
+          bundle exec license_finder --quiet
     strategy:
       matrix:
         gemfile:
```

**Comment by FGoessler** [comment]
Hi 👋 
We ran into this recently totally out of the blue in multiple repositories and it took us quite some time to find this possible resolution here.

Our repositories were working fine for over a year with the license_finder & bundler setup and now "suddenly" repositories started to run into this issue during routine gem updates. I guess the issue happens with newer bundler versions only?

For us it was mostly nokogiri that license_finder complained about not being able to find.

The workaround from @nbibler of using:
```
bundle config --local deployment false
bundle lock --add-platform x86_64-linux
bundle config --local deployment true
```
worked for us.

However I'd love to see this fixed on a general level since this is very unexpected behaviour and probably anyone using nokogiri (like a LOT of people since its a Rails depenency xD) will eventually run into this, right?

Hence I'd love this issue to be reopened and discuss how this can be move forward. :) 

Wdyt @xtreme-shane-lattanzio & @benjessop12 ?

**Comment by moeffju** [comment]
I just wanted to add that the workaround fixed this for me as well, I ran only `bundle lock --add-platform x86_64-linux`.

**Comment by stanhu** [comment]
I've confirmed this problem happens in bundler v2.2+. bundler v2.1.4 does not have this issue.

**Comment by stanhu** [comment]
I should note that this one-liner will work in CI on both ARM and x86 platforms:

```shel
BUNDLE_DEPLOYMENT=false BUNDLE_FROZEN=false bundle lock --add-platform `ruby -e "puts RUBY_PLATFORM"`
```

**Comment by akostadinov** [comment]
This works for me:
```
bundle exec license_finder ...
```

Probably once deps are already loaded by bundler, `license_finder` manages to find them. Also means `license_finder` has to be a project dependency.

**Comment by akostadinov** [comment]
Retracting my previous misguided comment. Actually it seems that Bundler behaves differently after being reset. See
https://github.com/rubygems/rubygems/issues/6626

So it is either a long-lived Bundler bug or LicenseFinder doesn't reset it properly.
