### ISSUE TITLE
LicenseFinder 6.14.1 breaks cocoapods license checking

### ISSUE THREAD

**Issue by hwo411** [pivotal/LicenseFinder#846]
Here is the log:

```
JSON::ParserError: 809: unexpected token at 'VolumesCIVolumegitlabNxNzMTKs0companynameprojectnamemobileappiosPodsTargetSupportFilesPods-ProjectnamePods-Projectname-acknowledgements.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “VolumesCIVolumegitlabNxNzMTKs0companynameprojectnamemobileappiosPodsTargetSupportFilesPods-ProjectnamePods-Projectname-acknowledgements.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=VolumesCIVolumegitlabNxNzMTKs0companynameprojectnamemobileappiosPodsTargetSupportFilesPods-ProjectnamePods-Projectname-acknowledgements.plist, NSUnderlyingError=0x7fb05ae0a740 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/json-2.5.1/lib/json/common.rb:216:in `parse'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/json-2.5.1/lib/json/common.rb:216:in `parse'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/package_managers/cocoa_pods.rb:56:in `read_plist'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/package_managers/cocoa_pods.rb:40:in `license_texts'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/package_managers/cocoa_pods.rb:18:in `block in current_packages'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/package_managers/cocoa_pods.rb:10:in `map'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/package_managers/cocoa_pods.rb:10:in `current_packages'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/package_manager.rb:105:in `current_packages_with_relations'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/scanner.rb:42:in `each'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/scanner.rb:42:in `flat_map'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/scanner.rb:42:in `active_packages'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/core.rb:83:in `current_packages'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/core.rb:78:in `decision_applier'
  /usr/local/Cellar/ruby@2.6/2.6.6_1/lib/ruby/2.6.0/forwardable.rb:224:in `any_packages?'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/license_aggregator.rb:15:in `map'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/lib/license_finder/cli/main.rb:113:in `action_items'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/gems/license_finder-6.14.1/bin/license_finder:6:in `<top (required)>'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/bin/license_finder:23:in `load'
  /Volumes/CI_Volume/Ruby/Gems/2.6.0/bin/license_finder:23:in `<top (required)>'
```

It might be that commit which introduced the problem: https://github.com/pivotal/LicenseFinder/commit/b0a61a2d833921c714cc39cdda8ba80af3f33d04

As you can see, all non-alphabetic symbols are stripped from the path.

I edited the project, company, volume and application names in the logs to the similar names (so that the problem would reproduce with them)

**Comment by xtreme-shane-lattanzio** [comment]
Hey @hwo411 Thanks for bringing this up. I just pushed a quick fix to not strip slashes which is most likely the issue. This should be fixed in the next release! https://github.com/pivotal/LicenseFinder/commit/f61d5a2dde5b3983d79330441e9b25215f37eb38

**Comment by blg-nb** [comment]
Hey, I need this fix. When is a new version coming?
