### ISSUE TITLE
Error loading dependency_decisions.yml after adding permitted license

### ISSUE THREAD

**Issue by AndreyArut92** [pivotal/LicenseFinder#871]
Hi guys,

I installed Ruby on Windows via Chocolatey (cinst) and then license_finder via gem.
Now I'm facing the issue when using it.

Steps to reproduce:
- create a new empty directory
- run the following command to add the license
```
> license_finder permitted_licenses add MIT
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Added MIT to the permitted licenses
```
- then try to run license_finder in the same directory, here is the error output
```
> license_finder
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
C:/tools/ruby31/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Time (Psych::DisallowedClass)
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/scalar_scanner.rb:109:in `parse_time'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/scalar_scanner.rb:52:in `tokenize'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:65:in `deserialize'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:128:in `visit_Psych_Nodes_Scalar'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `block in register_empty'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `each'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `register_empty'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `block in register_empty'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `each'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:338:in `register_empty'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
        from C:/tools/ruby31/lib/ruby/3.1.0/psych.rb:370:in `load'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/decisions.rb:283:in `restore'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/decisions.rb:273:in `fetch_saved'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/decisions_factory.rb:8:in `decisions'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/core.rb:56:in `decisions'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/core.rb:48:in `project_name'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/core.rb:94:in `options'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/core.rb:36:in `initialize'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/license_aggregator.rb:39:in `new'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/license_aggregator.rb:39:in `block in finders'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/license_aggregator.rb:37:in `map'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/license_aggregator.rb:37:in `finders'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/lib/license_finder/cli/main.rb:113:in `action_items'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/license_finder-6.15.0/bin/license_finder:6:in `<top (required)>'
        from C:/tools/ruby31/bin/license_finder:25:in `load'
        from C:/tools/ruby31/bin/license_finder:25:in `<main>'
```

**Comment by viktorianer** [comment]
No, it is not Windows only. I have similar issue on macOS.

```bash
$ bin/license_finder permitted_licenses add 'MIT'
$ bin/license_finder permitted_licenses add 'Apache 2.0'
.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Time (Psych::DisallowedClass)
...
.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/license_finder-6.0.0/bin/license_finder:6:in `<top (required)>'
	from bin/license_finder:29:in `load'
	from bin/license_finder:29:in `<main>'
```

I am on

```bash
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]
Rails 6.1.4.4
Darwin mbp-work.fritz.box 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

# or in Docker on
Linux 0107def2fb57 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 aarch64 Linux
```

**Comment by felixmohnert** [comment]
Same, on a Mac

**Comment by xtreme-shane-lattanzio** [comment]
Hey @felixmohnert @viktorianer @AndreyArut92 ! I believe this issue is the same as https://github.com/pivotal/LicenseFinder/issues/841 and a fix has been made. We will make a release soon so hopefully it helps everyone!

**Comment by felixmohnert** [comment]
Yes indeed, very much appreciated @xtreme-shane-lattanzio ! Thank you for the update.

**Comment by viktorianer** [comment]
> Hey @felixmohnert @viktorianer @AndreyArut92 ! I believe this issue is the same as #841 and a fix has been made. We will make a release soon so hopefully it helps everyone!

@felixmohnert it looks like it is fixed by [#877](https://github.com/pivotal/LicenseFinder/pull/877). Thanks a lot!
