### ISSUE TITLE
Maven  analysis error

### ISSUE THREAD

**Issue by xomak** [pivotal/LicenseFinder#874]
LicenseFinder::Maven: is active
Traceback (most recent call last):
        18: from /usr/local/bin/license_finder:25:in `<main>'
        17: from /usr/local/bin/license_finder:25:in `load'
        16: from /var/lib/gems/2.5.0/gems/license_finder-6.15.0/bin/license_finder:6:in `<top (required)>'
        15: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        14: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        13: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        12: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        11: from /var/lib/gems/2.5.0/gems/license_finder-6.15.0/lib/license_finder/cli/main.rb:113:in `action_items'
        10: from /var/lib/gems/2.5.0/gems/license_finder-6.15.0/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
         9: from /var/lib/gems/2.5.0/gems/license_finder-6.15.0/lib/license_finder/license_aggregator.rb:15:in `map'
         8: from /var/lib/gems/2.5.0/gems/license_finder-6.15.0/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
         7: from /usr/lib/ruby/2.5.0/forwardable.rb:223:in `any_packages?'
         6: from /var/lib/gems/2.5.0/gems/license_finder-6.15.0/lib/license_finder/core.rb:78:in `decision_applier'
         5: from /var/lib/gems/2.5.0/gems/license_finder-6.15.0/lib/license_finder/core.rb:83:in `current_packages'
         4: from /var/lib/gems/2.5.0/gems/license_finder-6.15.0/lib/license_finder/scanner.rb:42:in `active_packages'
         3: from /var/lib/gems/2.5.0/gems/license_finder-6.15.0/lib/license_finder/scanner.rb:42:in `flat_map'
         2: from /var/lib/gems/2.5.0/gems/license_finder-6.15.0/lib/license_finder/scanner.rb:42:in `each'
         1: from /var/lib/gems/2.5.0/gems/license_finder-6.15.0/lib/license_finder/package_manager.rb:105:in `current_packages_with_relations'
/var/lib/gems/2.5.0/gems/license_finder-6.15.0/lib/license_finder/package_managers/maven.rb:20:in `current_packages': Command 'mvn org.codehaus.mojo:license-maven-plugin:download-licenses' failed to execute:  (RuntimeError)

**Comment by sehirsig** [comment]
Have the same error. Problem is when there are faulty / old links in the pom.xml and the packages can't be downloaded, mvn install fails and crashes license_finder. maybe some way to skip the package if the link is invalid?

**Comment by xtreme-shane-lattanzio** [comment]
The maven code uses a plugin `./mvnw org.codehaus.mojo:license-maven-plugin:download-licenses`. Does that commandcause the issue? If so, we can't really filter or fix anything other than prepare no fail
