### ISSUE TITLE
Could not find nokogiri-1.13.3 in any of the sources

### ISSUE THREAD

**Issue by moeffju** [pivotal/LicenseFinder#897]
```
LicenseFinder::Bundler: Finished prepare on project
LicenseFinder::Yarn: Running prepare on project
LicenseFinder::Yarn: Finished prepare on project
LicenseFinder::Bundler: is installed
LicenseFinder::Yarn: is installed
LicenseFinder::Bundler: including groups [:default, :development, :staging, :production]
Traceback (most recent call last):
	24: from .../bin/license_finder:23:in `<main>'
	23: from .../bin/license_finder:23:in `load'
	22: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/bin/license_finder:6:in `<top (required)>'
	21: from .../lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	20: from .../lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	19: from .../lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	18: from .../lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	17: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/cli/main.rb:159:in `report'
	16: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:11:in `dependencies'
	15: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:49:in `aggregate_packages'
	14: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:49:in `flat_map'
	13: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:49:in `each'
	12: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:51:in `block in aggregate_packages'
	11: from .../lib/ruby/2.6.0/forwardable.rb:224:in `acknowledged'
	10: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/core.rb:79:in `decision_applier'
	 9: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/core.rb:84:in `current_packages'
	 8: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/scanner.rb:42:in `active_packages'
	 7: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/scanner.rb:42:in `flat_map'
	 6: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/scanner.rb:42:in `each'
	 5: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/package_manager.rb:105:in `current_packages_with_relations'
	 4: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/package_managers/bundler.rb:16:in `current_packages'
	 3: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/package_managers/bundler.rb:51:in `details'
	 2: from .../lib/ruby/gems/2.6.0/gems/license_finder-7.0.1/lib/license_finder/package_managers/bundler.rb:66:in `gem_details'
	 1: from .../lib/ruby/gems/2.6.0/gems/bundler-2.3.10/lib/bundler/definition.rb:240:in `specs_for'
.../lib/ruby/gems/2.6.0/gems/bundler-2.3.10/lib/bundler/definition.rb:481:in `materialize': Could not find nokogiri-1.13.3 in any of the sources (Bundler::GemNotFound)
```

`nokogiri` is not in the application's `Gemfile` directly, but referenced in `Gemfile.lock` as a dependency of two other gems:

```
    actiontext (6.1.3.2)
      actionpack (= 6.1.3.2)
      activerecord (= 6.1.3.2)
      activestorage (= 6.1.3.2)
      activesupport (= 6.1.3.2)
      nokogiri (>= 1.8.5)
…
    capybara (3.36.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
…
    loofah (2.15.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
```

and also directly:

```
    nokogiri (1.13.3)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
```

The prepare step works fine, but the actual analysis then fails – I’m guessing that it’s not loading the right nokogiri in the end, but I have no clue how to further debug this unfortunately.

(Docker does not work for this either as neither the dlf tool nor direct invocation even manage to get the right ruby going, somehow - I opened another issue for that).

**Comment by moeffju** [comment]
(Obviously, I might be missing something, in which case I would appreciate pointers as well :) )

**Comment by moeffju** [comment]
This might be the same as #862 and #828

**Comment by xtreme-shane-lattanzio** [comment]
Duplicate
