### ISSUE TITLE
LF fails to recognize installed pip deps if name differs on pypi

### ISSUE THREAD

**Issue by sdo2hi** [pivotal/LicenseFinder#901]
Environment:
* Python 3.10
* requirements.txt with content:
* `ruamel-yaml-clib==0.2.6`
* run license_finder

Observation:
license_finder_pip.py exits with DistributionNotFound even though the dependency is installed. This is related to canonicalization of project names. If the requirements.txt is modified to replace dashes with dots, it works.

https://pypi.org/project/ruamel.yaml.clib/ reports the original project name with dots. But both formats are supported by pip install. 

The big issue here is that we are generating requirements.txt files automatically using pip compile and pip freeze. These will always report `ruamel-yaml-clib` with dashes instead of dots. 

I'm guessing license finder should be able to support the different formats supported by pip.

**Comment by xtreme-shane-lattanzio** [comment]
@sdo2hi So I managed to repro this by using the LF docker image, making a requirements.txt with just `ruamel-yaml-clib==0.2.6` inside with dots instead and using `pip3 install -r requirements.txt` followed by `python3 ../bin/license_finder_pip.py requirements.txt` That worked and then I swapped it back to dashes which failed.

Narrowing it down, the line failing is when it tried to parse with `pkg_resources.working_set.resolve(reqs)`. This means the issue is actually compatibility with the pip versions as per this github issue:https://github.com/jazzband/pip-tools/issues/1576

I don't know if I'm crazy but I cannot get the 62.0 version of the setuptools installed which is what that thread suggests. If you want to try this out and potentially make a change to the docker image, it should get this green. It may need a pip3 version bump to get the new version of setuptools but I am not sure. Let me know if you can throw up a PR and we will get this merged!

**Comment by arulrajnet** [comment]
I am facing the same issue. My `requirements.txt` is

```
staticjinja==5.0.0
```

I used docker to run

```
docker run --rm -v $PWD:/src licensefinder/license_finder /bin/bash -lc "cd /src && license_finder report > licenses.csv"
```

The error I got is

```
LicenseFinder::Pip: [32mis active for '/src'[0m
pip3 install: [31mdid not succeed.[0m
pip3 install: [31mLicenseFinder command 'python3 /usr/share/rvm/gems/ruby-3.2.3/gems/license_finder-7.2.1/bin/license_finder_pip.py /src/requirements.txt' failed:
	Traceback (most recent call last):
  File "/usr/share/rvm/gems/ruby-3.2.3/gems/license_finder-7.2.1/bin/license_finder_pip.py", line 42, in <module>
    packages = [transform(dist) for dist in pkg_resources.working_set.resolve(reqs)]
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pip._vendor.pkg_resources.DistributionNotFound: The 'staticjinja==5.0.0' distribution was not found and is required by the application
[0m
```

**Comment by arulrajnet** [comment]
> I am facing the same issue. My `requirements.txt` is
> 
> ```
> staticjinja==5.0.0
> ```
> 
> I used docker to run
> 
> ```
> docker run --rm -v $PWD:/src licensefinder/license_finder /bin/bash -lc "cd /src && license_finder report > licenses.csv"
> ```
> 
> The error I got is
> 
> ```
> LicenseFinder::Pip: �[32mis active for '/src'�[0m
> pip3 install: �[31mdid not succeed.�[0m
> pip3 install: �[31mLicenseFinder command 'python3 /usr/share/rvm/gems/ruby-3.2.3/gems/license_finder-7.2.1/bin/license_finder_pip.py /src/requirements.txt' failed:
> 	Traceback (most recent call last):
>   File "/usr/share/rvm/gems/ruby-3.2.3/gems/license_finder-7.2.1/bin/license_finder_pip.py", line 42, in <module>
>     packages = [transform(dist) for dist in pkg_resources.working_set.resolve(reqs)]
>   File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 786, in resolve
>     raise DistributionNotFound(req, requirers)
> pip._vendor.pkg_resources.DistributionNotFound: The 'staticjinja==5.0.0' distribution was not found and is required by the application
> �[0m
> ```

This is solved after install the packages like below

```
docker run --rm -v $PWD:/src licensefinder/license_finder /bin/bash -lc "cd /src && pip install -r requirements.txt && license_finder report > licenses.csv"
```
