### ISSUE TITLE
calico - Getting the dependencies from go list failed

### ISSUE THREAD

**Issue by carlowahlstedt** [pivotal/LicenseFinder#917]
Running `license_finder report` on `calico` fails.

License Finder Version: 7.0.1

Error:
```bash
LicenseFinder::GoModules: is active
GO111MODULE=on go list -mod=readonly -deps -f '{{ if and (.DepOnly) (.Module) (not .Standard) }}{{ $mod := (or .Module.Replace .Module) }}{{ $mod.Path }},{{ $mod.Version }},{{ or $mod.Dir .Dir }}{{ end }}' ./...: did not succeed.
GO111MODULE=on go list -mod=readonly -deps -f '{{ if and (.DepOnly) (.Module) (not .Standard) }}{{ $mod := (or .Module.Replace .Module) }}{{ $mod.Path }},{{ $mod.Version }},{{ or $mod.Dir .Dir }}{{ end }}' ./...: Getting the dependencies from go list failed
	package github.com/projectcalico/calico/cni-plugin/internal/pkg/utils/winpol
	imports github.com/projectcalico/calico/cni-plugin/internal/pkg/utils/hcn: build constraints exclude all Go files in /Users/carlo.wahlstedt/temp-chg/calico/cni-plugin/internal/pkg/utils/hcn
package github.com/projectcalico/calico/felix/dataplane/windows
	imports github.com/projectcalico/calico/felix/dataplane/windows/hcn: build constraints exclude all Go files in /Users/carlo.wahlstedt/temp-chg/calico/felix/dataplane/windows/hcn
package github.com/projectcalico/calico/felix/dataplane/windows
	imports github.com/projectcalico/calico/felix/dataplane/windows/hns: build constraints exclude all Go files in /Users/carlo.wahlstedt/temp-chg/calico/felix/dataplane/windows/hns
package github.com/projectcalico/calico/node/cmd/calico-node
	imports github.com/projectcalico/calico/node/cmd/calico-node/bpf: build constraints exclude all Go files in /Users/carlo.wahlstedt/temp-chg/calico/node/cmd/calico-node/bpf
package github.com/projectcalico/calico/node/cmd/calico-node
	imports github.com/projectcalico/calico/node/pkg/lifecycle/startup
	imports github.com/projectcalico/calico/node/pkg/lifecycle/startup/autodetection/ipv4: build constraints exclude all Go files in /Users/carlo.wahlstedt/temp-chg/calico/node/pkg/lifecycle/startup/autodetection/ipv4
package github.com/projectcalico/calico/node/cmd/calico-node
	imports github.com/projectcalico/calico/node/pkg/nodeinit: build constraints exclude all Go files in /Users/carlo.wahlstedt/temp-chg/calico/node/pkg/nodeinit

/usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/package_managers/go_modules.rb:63:in `block in packages_info': Command 'GO111MODULE=on go list -mod=readonly -deps -f '{{ if and (.DepOnly) (.Module) (not .Standard) }}{{ $mod := (or .Module.Replace .Module) }}{{ $mod.Path }},{{ $mod.Version }},{{ or $mod.Dir .Dir }}{{ end }}' ./...' failed to execute (RuntimeError)
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/package_managers/go_modules.rb:32:in `chdir'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/package_managers/go_modules.rb:32:in `packages_info'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/package_managers/go_modules.rb:20:in `current_packages'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/package_manager.rb:105:in `current_packages_with_relations'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/scanner.rb:42:in `each'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/scanner.rb:42:in `flat_map'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/scanner.rb:42:in `active_packages'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/core.rb:84:in `current_packages'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/core.rb:79:in `decision_applier'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:224:in `acknowledged'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:51:in `block in aggregate_packages'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:49:in `each'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:49:in `flat_map'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:49:in `aggregate_packages'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:11:in `dependencies'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/lib/license_finder/cli/main.rb:159:in `report'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/gems/license_finder-7.0.1/bin/license_finder:6:in `<top (required)>'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/bin/license_finder:23:in `load'
	from /usr/local/Cellar/licensefinder/7.0.1/libexec/bin/license_finder:23:in `<main>'
```

Steps to reproduce:
1. Run: `git clone https://github.com/projectcalico/calico`
2. Inside the calico dir run: `license_finder report`

**Comment by xtreme-shane-lattanzio** [comment]
Hey @carlowahlstedt ! It looks liek there is a go version mismatch. The docker image actually uses `1.14.3` which is quite old! We should probably upgrade that but in the mean time you can run something like `wget https://dl.google.com/go/go1.18.linux-amd64.tar.gz && tar -xvf go1.18.linux-amd64.tar.gz && rm -rf /go && mv go / && rm go1.18.linux-amd64.tar.gz` to get this working!

**Comment by carlowahlstedt** [comment]
Just tried it and latest version of go does indeed work for me! Thanks for looking into it!
