### ISSUE TITLE
Can't run, "Could not find nokogiri-1.13.8 in any of the sources"

### ISSUE THREAD

**Issue by jrochkind** [pivotal/LicenseFinder#929]
I am trying to `gem install license_finder` and run as `license_finder` per README instructions. 

I am trying to use it in a ruby project with a `Gemfile`. 

But:

```
jrochkind-shi scihist_digicoll (master ?) $ gem install license_finder
Fetching license_finder-7.0.1.gem
Fetching with_env-1.1.0.gem
Fetching xml-simple-1.1.9.gem
Successfully installed xml-simple-1.1.9
Successfully installed with_env-1.1.0
Successfully installed license_finder-7.0.1
3 gems installed

jrochkind-shi scihist_digicoll (master ?) $ license_finder
LicenseFinder::Bundler: is active
LicenseFinder::NPM: is active
LicenseFinder::Yarn: is active
/Users/jrochkind/.gem/ruby/3.0.4/gems/bundler-2.3.14/lib/bundler/definition.rb:486:in `materialize': Could not find nokogiri-1.13.8 in any of the sources (Bundler::GemNotFound)
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/bundler-2.3.14/lib/bundler/definition.rb:241:in `specs_for'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/package_managers/bundler.rb:66:in `gem_details'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/package_managers/bundler.rb:51:in `details'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/package_managers/bundler.rb:16:in `current_packages'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/package_manager.rb:105:in `current_packages_with_relations'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/scanner.rb:42:in `each'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/scanner.rb:42:in `flat_map'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/scanner.rb:42:in `active_packages'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/core.rb:84:in `current_packages'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/core.rb:79:in `decision_applier'
	from /Users/jrochkind/.rubies/ruby-3.0.4/lib/ruby/3.0.0/forwardable.rb:232:in `any_packages?'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:15:in `map'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder/cli/main.rb:119:in `action_items'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/bin/license_finder:6:in `<top (required)>'
	from /Users/jrochkind/.gem/ruby/3.0.4/bin/license_finder:25:in `load'
	from /Users/jrochkind/.gem/ruby/3.0.4/bin/license_finder:25:in `<main>'
```

Maybe somehow modern bundler is doing something automatically even though I didn't run `bundle exec license_finder`, becuase my project uses bundler, and in fact any project using bundler _has_ to put license_finder in Gemfile? Should README be changed to recommend this?

If I do add `license_finder` to `Gemfile` and `bundle exec license_finder` instead, it does work. 

But now I have to deal with:

> but can pull in unwanted dependencies, including bundler. To mitigate this problem, see [Excluding Dependencies](https://github.com/pivotal/LicenseFinder#excluding-dependencies).

**Comment by xtreme-shane-lattanzio** [comment]
This is definitely an environment issue. Bundler is always changing stuff and when we fix it one way it breaks another. Just to test this quick, I pulled the default ruby docker image and ran `gem install license_finder --install-dir /usr/local/lib/ruby/gems/3.1.0` and it all seemed to work. Is there a specific image that you are getting this error on?

It just looks like license finder is being installed in a different folder than where the rest of your gems are

**Comment by jrochkind** [comment]
Hi, thanks for the response!

I am not using a docker image for my ruby environment, I don't use docker. 

> It just looks like license finder is being installed in a different folder than where the rest of your gems are

I have never run into such a thing before, I don't know how gems would wind up in different folders. 

It also does not SEEM to be true to me.  All my gems seem to be in `/Users/jrochkind/.gem/ruby/3.0.4/gems`

Eg:

```
jrochkind-shi scihist_digicoll (master ?) $ gem which license_finder
/Users/jrochkind/.gem/ruby/3.0.4/gems/license_finder-7.0.1/lib/license_finder.rb

jrochkind-shi scihist_digicoll (master ?) $ gem which rake
/Users/jrochkind/.gem/ruby/3.0.4/gems/rake-13.0.6/lib/rake.rb

jrochkind-shi scihist_digicoll (master ?) $ bundle show rake
/Users/jrochkind/.gem/ruby/3.0.4/gems/rake-13.0.6
```

Where are you seeing the evidence that some of my gems are installed in a different place, and what is that place?

I do use `chruby` as a ruby version manager, perhaps it's somehow incompatible with license_finder? I have not previously run into any problems like this in years of using `chruby`, it's ordinarily pretty solid. 

(Note: I can use license_finder by adding it to my Gemfile and using `bundle exec`, but I agree with README that this is undesirable).

**Comment by xtreme-shane-lattanzio** [comment]
Just playing in a fresh environment, the output of `gem env` is:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.7
  - RUBY VERSION: 3.1.2 (2022-04-12 patchlevel 20) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/bundle
  - USER INSTALLATION DIRECTORY: /root/.local/share/gem/ruby/3.1.0
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/bundle/bin
  - SPEC CACHE DIRECTORY: /root/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /usr/local/bundle
     - /root/.local/share/gem/ruby/3.1.0
     - /usr/local/lib/ruby/gems/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-document"
     - "update" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
```

The gem path being used is ` /usr/local/lib/ruby/gems/3.1.0/gems/` but when installing license finder with `gem install`, license finder is installed into `/usr/local/bundle/gems/`. That is all I meant by changing the install directory. chruby would change this though. I use rvm and have this gems in an rvm specific folder

**Comment by wxnc-haffi** [comment]
I had the same problem, solved by forcing ruby platform in bundle config: https://stackoverflow.com/questions/69807153/macos-m1-arm64-unable-to-load-nokogiri-using-system-default-ruby
