### ISSUE TITLE
pip2 fails with "distribution was not found and is required by the application" on dotted package names

### ISSUE THREAD

**Issue by DavidS-cloud** [pivotal/LicenseFinder#931]
requirements.in:
```
boolean.py
```
requirements.txt:
```
#
# This file is autogenerated by pip-compile with python 3.10
# To update, run:
#
#    pip-compile --output-file=requirements.txt requirements.in
#
boolean-py==4.0
    # via -r requirements.in
```

Running license_finder:
```
✦ ❯ docker run -v $PWD:/scan -it licensefinder/license_finder bash -lc "cd /scan && license_finder action_items --prepare --enabled-package-managers=pip"
LicenseFinder::Pip: is active
pip2 install: did not succeed.
pip2 install: LicenseFinder command 'python /usr/share/rvm/gems/ruby-3.1.1/gems/license_finder-7.0.1/bin/license_finder_pip.py /scan/requirements.txt' failed:
	Traceback (most recent call last):
  File "/usr/share/rvm/gems/ruby-3.1.1/gems/license_finder-7.0.1/bin/license_finder_pip.py", line 42, in <module>
    packages = [transform(dist) for dist in pkg_resources.working_set.resolve(reqs)]
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pip._vendor.pkg_resources.DistributionNotFound: The 'boolean-py==4.0' distribution was not found and is required by the application


No dependencies recognized!

✦ ❯ 
```

Expected outcome: license_finder successfully prepares and scans the requirements.

**Comment by xtreme-shane-lattanzio** [comment]
Hey @DavidS-cloud ! Do you know why the dot was converted to a dash in the requirements.txt? That is the only reason this seems to be failing. I'm wondering if we are supposed to be changing https://github.com/pivotal/LicenseFinder/blob/master/bin/license_finder_pip.py to account for this

**Comment by DavidS-cloud** [comment]
I wish I knew! This is happening on a default pip-compile install with no additional options and I'm seeing this translation for several packages. Notably, PyPI also accepts the dash-version and redirects to the dotted version: https://pypi.org/project/boolean-py/

**Comment by dflock** [comment]
Python package names are normalized when serving them from package repositories like pypi: https://peps.python.org/pep-0503/#normalized-names

They are also _sometimes_ normalized when saving them into requirements/lock files - I know that `poetry` does this - and it looks like `pip-compile` does too. Regular `pip` doesn't do this when doing `pip freeze` or `pip list`.

This happens fairly rarely - because almost all python packages use simple ascii shortnames with no punctuation, but some - like `ruamel.yaml` or `boolean.py` have chars that will get replaced by a dash.

**Comment by dflock** [comment]
This is related to #901 & #943
