### ISSUE TITLE
`license_finder` fails with RuntimeError when using pnpm in a Github Action

### ISSUE THREAD

**Issue by burmudar** [pivotal/LicenseFinder#969]
When `license_finder` is executed within a Github action I ecounter the following error
```
LicenseFinder::GoModules: is active
LicenseFinder::Go15VendorExperiment: is active
LicenseFinder::NPM: is active
LicenseFinder::PNPM: is active
/opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/package_managers/pnpm.rb:35:in `current_packages': Command 'pnpm licenses list --json --long --no-color --recursive --dir /home/runner/work/sourcegraph/sourcegraph' failed to execute:  (RuntimeError)
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/package_manager.rb:105:in `current_packages_with_relations'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/scanner.rb:42:in `each'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/scanner.rb:42:in `flat_map'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/scanner.rb:42:in `active_packages'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/core.rb:84:in `current_packages'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/core.rb:79:in `decision_applier'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/3.1.0/forwardable.rb:232:in `any_packages?'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:15:in `map'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/cli/main.rb:121:in `action_items'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/bin/license_finder:6:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/bin/license_finder:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.1.3/x64/bin/license_finder:25:in `<main>'
```
Note:
* Node version: 16.18.7
* pnpm versions: 2.24 and 2.27.0

**Comment by burmudar** [comment]
I found the issue. I had to rerun `pnpm deduplicate` again, which remove some dependent projects I previously removed locally but was still referred to in the `pnpm-lock.yaml`
