### ISSUE TITLE
GitHub Rate Limit

### ISSUE THREAD

**Issue by hypery2k** [pivotal/LicenseFinder#971]
First, thanks for the awesome project. I'm running in the GitHub Rate Limit:
```
WARNING: Invalid cookie header: "Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Sat, 16 Mar 2024 04:53:07 GMT; HttpOnly; Secure; SameSite=Lax". Invalid 'expires' attribute: Sat, 16 Mar 2024 04:53:07 GMT
	from /Users/mreinhardt/.gems/gems/license_finder-7.1.0/lib/license_finder/package_manager.rb:105:in `current_packages_with_relations'
	from /Users/mreinhardt/.gems/gems/license_finder-7.1.0/lib/license_finder/scanner.rb:42:in `each'
	from /Users/mreinhardt/.gems/gems/license_finder-7.1.0/lib/license_finder/scanner.rb:42:in `flat_map'
	from /Users/mreinhardt/.gems/gems/license_finder-7.1.0/lib/license_finder/scanner.rb:42:in `active_packages'
	from /Users/mreinhardt/.gems/gems/license_finder-7.1.0/lib/license_finder/core.rb:84:in `current_packages'
	from /Users/mreinhardt/.gems/gems/license_finder-7.1.0/lib/license_finder/core.rb:79:in `decision_applier'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:224:in `acknowledged'
	from /Users/mreinhardt/.gems/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:51:in `block in aggregate_packages'
	from /Users/mreinhardt/.gems/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:49:in `each'
```

Is it somehow possible to set Headers via CLI option to add a GitHub Api Token to all requests?

**Comment by xtreme-shane-lattanzio** [comment]
Hey @hypery2k I dont think I've seen rate limit issues like this. You should be able to log in in the script that runs LF so that this is avoided. You shouldnt need a header in LF calls themselves.
