### ISSUE TITLE
LF is trying to open nuget.exe on macos / linux

### ISSUE THREAD

**Issue by blumendorf** [pivotal/LicenseFinder#975]
I am running LF locally on macos and on ubuntu-latest in an Azure Pipeline.
Our goal is to screen a list of repositories (yarn, npm, nuget and pip) in one go.

In both setups I am seeing errors where it tries to find nuget.exe, which will probably not succeed in these environments.

On macos the error is this
```
LicenseFinder::Nuget: is active
mono /usr/local/bin/nuget.exe restore: did not succeed.
mono /usr/local/bin/nuget.exe restore: Cannot open assembly '/usr/local/bin/nuget.exe': No such file or directory.

Traceback (most recent call last):
        18: from /Users/user/.rbenv/versions/2.7.5/bin/license_finder:23:in `<main>'
        17: from /Users/user/.rbenv/versions/2.7.5/bin/license_finder:23:in `load'
        16: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/bin/license_finder:6:in `<top (required)>'
        15: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        14: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        13: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        12: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        11: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/lib/license_finder/cli/main.rb:161:in `report'
        10: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:11:in `dependencies'
         9: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:49:in `aggregate_packages'
         8: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:49:in `flat_map'
         7: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:49:in `each'
         6: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:50:in `block in aggregate_packages'
         5: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/lib/license_finder/core.rb:63:in `prepare_projects'
         4: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/lib/license_finder/core.rb:63:in `each'
         3: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/lib/license_finder/core.rb:65:in `block in prepare_projects'
         2: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/lib/license_finder/package_managers/nuget.rb:98:in `prepare'
         1: from /Users/user/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/lib/license_finder/package_managers/nuget.rb:98:in `chdir'
/Users/marcoblumendorf/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/license_finder-7.1.0/lib/license_finder/package_managers/nuget.rb:117:in `block in prepare': Prepare command 'mono /usr/local/bin/nuget.exe restore' failed (RuntimeError)
Cannot open assembly '/usr/local/bin/nuget.exe': No such file or directory.
```

On ubuntu in the Azure pipeline I am seeing this:
```
LicenseFinder::Nuget: is active
/opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/package_managers/nuget.rb:117:in `block in prepare': Prepare command 'mono /usr/local/bin/nuget.exe restore' failed (RuntimeError)
Cannot open assembly '/usr/local/bin/nuget.exe': No such file or directory.
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/package_managers/nuget.rb:98:in `chdir'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/package_managers/nuget.rb:98:in `prepare'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/core.rb:65:in `block in prepare_projects'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/core.rb:63:in `each'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/core.rb:63:in `prepare_projects'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:50:in `block in aggregate_packages'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:49:in `each'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:49:in `flat_map'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:49:in `aggregate_packages'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/license_aggregator.rb:11:in `dependencies'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/lib/license_finder/cli/main.rb:161:in `report'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/license_finder-7.1.0/bin/license_finder:6:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/bin/license_finder:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/bin/license_finder:25:in `'
mono /usr/local/bin/nuget.exe restore: did not succeed.
mono /usr/local/bin/nuget.exe restore: Cannot open assembly '/usr/local/bin/nuget.exe': No such file or directory.
```

I am not a .net developer, so I might be doing something wrong in my setup of nuget here.

**Comment by blumendorf** [comment]
My bad, I think I figured it out.
I originally thought the mono part of the script was some kind of fallback and did not realise that it was the only way used to call nuget on non-windows systems.

I installed nuget using `brew install nuget` on macos and using `NuGetToolInstaller` on Azure.
With this, the `nuget` command works directly without mono (instead of `mono /usr/local/bin/nuget.exe`).

As mentioned, I am not a .net developer, so I am not sure about the implications, but it would be nice, to either support both approaches, or document which approach one needs to take to get this working.

This would also be helpful for other package managers.
I.e. a brief description of what LF needs to have installed for each package manager to work.

Maybe this exists already, but I could not find it.
